/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import guiComponents.RangeSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Peppe
 */
public class PannelloFiltri extends javax.swing.JPanel {

    /**
     * Creates new form PannelloFiltri
     */
    public PannelloFiltri(int minDeg,int maxDeg,int minInDeg,int maxInDeg) {
        initComponents();
        lblmaxDegree.setText(""+maxDeg);
        lblmaxInDegree.setText(""+maxInDeg);
        lblmaxEdge.setText(""+1);
        
        degreeSlider.setMinimum(minDeg);
        degreeSlider.setMaximum(maxDeg);
        degreeSlider.setValue(minDeg);
        degreeSlider.setUpperValue(maxDeg);
        // Add listener to update display.
        degreeSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                RangeSlider slider = (RangeSlider) e.getSource();
                lblminDegree.setText(String.valueOf(slider.getValue()));
                lblmaxDegree.setText(String.valueOf(slider.getUpperValue()));
            }
        });
        inDegreeSlider.setMinimum(minDeg);
        inDegreeSlider.setMaximum(maxDeg);
        inDegreeSlider.setValue(minDeg);
        inDegreeSlider.setUpperValue(maxDeg);
        // Add listener to update display.
        inDegreeSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                RangeSlider slider = (RangeSlider) e.getSource();
                lblminInDegree.setText(String.valueOf(slider.getValue()));
                lblmaxInDegree.setText(String.valueOf(slider.getUpperValue()));
            }
        });
        
        edgeSlider.setMinimum(minDeg);
        edgeSlider.setMaximum(maxDeg);
        edgeSlider.setValue(minDeg);
        edgeSlider.setUpperValue(maxDeg);
        // Add listener to update display.
        edgeSlider.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent e) {
                RangeSlider slider = (RangeSlider) e.getSource();
                lblminEdge.setText(""+(double)slider.getValue()/1000);
                lblmaxEdge.setText(""+(double)slider.getUpperValue()/1000);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblnodi = new javax.swing.JLabel();
        lblarchi = new javax.swing.JLabel();
        btnVista = new javax.swing.JButton();
        btnMostra = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        degreeSlider = new guiComponents.RangeSlider();
        inDegreeSlider = new guiComponents.RangeSlider();
        edgeSlider = new guiComponents.RangeSlider();
        lblminimo1 = new javax.swing.JLabel();
        lblminDegree = new javax.swing.JLabel();
        lblMassimo1 = new javax.swing.JLabel();
        lblmaxDegree = new javax.swing.JLabel();
        lblminimo2 = new javax.swing.JLabel();
        lblminInDegree = new javax.swing.JLabel();
        lblmassimo2 = new javax.swing.JLabel();
        lblmaxInDegree = new javax.swing.JLabel();
        lblminimo3 = new javax.swing.JLabel();
        lblmassimo3 = new javax.swing.JLabel();
        lblminEdge = new javax.swing.JLabel();
        lblmaxEdge = new javax.swing.JLabel();
        checkEdge = new javax.swing.JCheckBox();
        checkInDegree = new javax.swing.JCheckBox();
        checkDegree = new javax.swing.JCheckBox();
        btnApplica = new javax.swing.JButton();

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.jLayeredPane1.border.title"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLayeredPane1, org.jdesktop.beansbinding.ObjectProperty.create(), jLayeredPane1, org.jdesktop.beansbinding.BeanProperty.create("border"), "Informazioni Grafo");
        bindingGroup.addBinding(binding);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.jLabel1.text")); // NOI18N
        jLabel1.setBounds(10, 20, 40, 14);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.jLabel2.text")); // NOI18N
        jLabel2.setBounds(10, 50, 28, 14);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblnodi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblnodi, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblnodi.text")); // NOI18N
        lblnodi.setBounds(60, 20, 70, 14);
        jLayeredPane1.add(lblnodi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblarchi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblarchi, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblarchi.text")); // NOI18N
        lblarchi.setBounds(80, 50, 50, 14);
        jLayeredPane1.add(lblarchi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.openide.awt.Mnemonics.setLocalizedText(btnVista, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.btnVista.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnMostra, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.btnMostra.text")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.jPanel1.border.title"))); // NOI18N

        degreeSlider.setPaintLabels(true);
        degreeSlider.setPaintTicks(true);
        degreeSlider.setSnapToTicks(true);

        inDegreeSlider.setPaintLabels(true);
        inDegreeSlider.setPaintTicks(true);
        inDegreeSlider.setSnapToTicks(true);

        edgeSlider.setPaintLabels(true);
        edgeSlider.setPaintTicks(true);
        edgeSlider.setSnapToTicks(true);

        org.openide.awt.Mnemonics.setLocalizedText(lblminimo1, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminimo1.text")); // NOI18N

        lblminDegree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblminDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminDegree.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblMassimo1, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblMassimo1.text")); // NOI18N

        lblmaxDegree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblmaxDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblmaxDegree.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblminimo2, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminimo2.text")); // NOI18N

        lblminInDegree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblminInDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminInDegree.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblmassimo2, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblmassimo2.text")); // NOI18N

        lblmaxInDegree.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblmaxInDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblmaxInDegree.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblminimo3, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminimo3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblmassimo3, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblmassimo3.text")); // NOI18N

        lblminEdge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblminEdge, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblminEdge.text")); // NOI18N

        lblmaxEdge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        org.openide.awt.Mnemonics.setLocalizedText(lblmaxEdge, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.lblmaxEdge.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(checkEdge, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.checkEdge.text")); // NOI18N
        checkEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEdgeActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(checkInDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.checkInDegree.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(checkDegree, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.checkDegree.text")); // NOI18N
        checkDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkDegreeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(inDegreeSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(edgeSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(degreeSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(lblminimo3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblminEdge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblmassimo3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, 0)
                        .add(lblmaxEdge, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(lblminimo1)
                                .add(0, 0, 0)
                                .add(lblminDegree, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(checkDegree))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblMassimo1)
                        .add(0, 0, 0)
                        .add(lblmaxDegree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(checkEdge)
                            .add(checkInDegree)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(lblminimo2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(lblminInDegree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(lblmassimo2)
                        .add(0, 0, 0)
                        .add(lblmaxInDegree, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(checkDegree)
                        .add(0, 0, 0)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblminimo1)
                            .add(lblminDegree)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblMassimo1)
                        .add(lblmaxDegree)))
                .add(degreeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(checkInDegree)
                .add(0, 0, 0)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblminimo2)
                    .add(lblminInDegree)
                    .add(lblmaxInDegree)
                    .add(lblmassimo2))
                .add(0, 0, Short.MAX_VALUE)
                .add(inDegreeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(checkEdge)
                .add(0, 0, 0)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblminimo3)
                            .add(lblminEdge)
                            .add(lblmaxEdge))
                        .add(0, 0, 0)
                        .add(edgeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(lblmassimo3))
                .add(0, 0, 0))
        );

        org.openide.awt.Mnemonics.setLocalizedText(btnApplica, org.openide.util.NbBundle.getMessage(PannelloFiltri.class, "PannelloFiltri.btnApplica.text")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnVista)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnApplica, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnMostra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnVista, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(btnApplica))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(btnMostra)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void checkDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkDegreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkDegreeActionPerformed

    private void checkEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEdgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkEdgeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplica;
    private javax.swing.JToggleButton btnMostra;
    private javax.swing.JButton btnVista;
    private javax.swing.JCheckBox checkDegree;
    private javax.swing.JCheckBox checkEdge;
    private javax.swing.JCheckBox checkInDegree;
    private guiComponents.RangeSlider degreeSlider;
    private guiComponents.RangeSlider edgeSlider;
    private guiComponents.RangeSlider inDegreeSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMassimo1;
    private javax.swing.JLabel lblarchi;
    private javax.swing.JLabel lblmassimo2;
    private javax.swing.JLabel lblmassimo3;
    private javax.swing.JLabel lblmaxDegree;
    private javax.swing.JLabel lblmaxEdge;
    private javax.swing.JLabel lblmaxInDegree;
    private javax.swing.JLabel lblminDegree;
    private javax.swing.JLabel lblminEdge;
    private javax.swing.JLabel lblminInDegree;
    private javax.swing.JLabel lblminimo1;
    private javax.swing.JLabel lblminimo2;
    private javax.swing.JLabel lblminimo3;
    private javax.swing.JLabel lblnodi;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public RangeSlider getDegreeSlider(){
    	return degreeSlider;
    }
    public RangeSlider getInDegreeSlider(){
    	return inDegreeSlider;
    }
    public RangeSlider getEdgeSlider(){
    	return edgeSlider;
    }
public void setDegreeUpperValue(int max){
        degreeSlider.setMaximum(max);
        degreeSlider.setUpperValue(max);
    	this.lblminDegree.setText(String.valueOf(degreeSlider.getValue()));
        this.lblmaxDegree.setText(String.valueOf(degreeSlider.getUpperValue()));
    }
public void setInDegreeUpperValue(int max){
        inDegreeSlider.setMaximum(max);
        inDegreeSlider.setUpperValue(max);
    	this.lblminInDegree.setText(String.valueOf(inDegreeSlider.getValue()));
        this.lblmaxInDegree.setText(String.valueOf(inDegreeSlider.getUpperValue()));
    }
public void setInfo(int archi,int nodi){
    lblarchi.setText(""+archi);
    lblnodi.setText(""+nodi);
}
}
